name: Publish Web

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: npm install
      - name: Build Web
        run: npm build
